### PR TITLE
Empty line stripping fix

### LINKED ISSUE #447: Unexpected newline removal
After https://github.com/sunng87/handlebars-rust/pull/404, it seems lines are being removed a bit too aggressively.  If I have a template like this:

```
{{#if a}}x{{/if}}
y
```

I would expect it to render like this, if the data is `{"a": true}`:

```
x
y
```

This is what happens in handlebars.js, which I tested on [tryhandlebarsjs.com](http://tryhandlebarsjs.com/).

In handlebars-rust 4, this renders as:

```
xy
```

### PR DESCRIPTION
**Pull request by sunng87**
Fixes #447

### CODE REVIEW

**Comment by sunng87** [comment]
This cannot easily be fixed from pest parser level. I'm looking into template parser to resolve this.

Rules for whitespace auto elimination is to check if the directive `{{# xxx}}`` and ``{{/ xxx}}` is holding a whole line, with leading and trailing whitespaces counted, and then remove the trailing `NEWLINE` and keep the leading one.

**Comment by sunng87** [comment]
The original JavaScript version: https://github.com/handlebars-lang/handlebars.js/pull/787

File: src/template.rs [hunk 1]
```diff
@@ -389,10 +389,36 @@ impl Template {
         }
     }
 
+    fn check_previous_rawstring_for_newline(template_stack: &VecDeque<Template>) -> bool {
+        let t = template_stack.front().unwrap();
+        if let Some(el) = t.elements.get(0) {
```
Comment (sunng87) [inline src/template.rs:394]: get last element of the template

**Review by sunng87 — COMMENTED** [review]
leading whitespace has to be removed too

File: src/template.rs [hunk 2]
```diff
@@ -442,22 +480,14 @@ impl Template {
...
-                !matches!(
-                    p.as_rule(),
-                    Rule::escape
-                        | Rule::brackets_open
-                        | Rule::brackets_close
-                        | Rule::double_brackets_open
-                        | Rule::double_brackets_close
-                        | Rule::comment_brackets_open
-                )
+                !matches!(p.as_rule(), Rule::escape | Rule::helper_block)
```
Comment (sunng87) [inline src/template.rs:490]: remove `Rule::helper_block`

File: src/template.rs [hunk 3]
```diff
@@ -433,6 +469,8 @@ impl Template {
         let mut template_stack: VecDeque<Template> = VecDeque::new();
 
         let mut omit_pro_ws = false;
+        // flag for tracking standalone statement like {{#if}} and {{/if}}
```
Comment (sunng87) [inline src/template.rs:472]: update comment to clarify its purpose

File: src/template.rs [hunk 4]
```diff
@@ -554,6 +598,13 @@ impl Template {
                         }
                         omit_pro_ws = exp.omit_pro_ws;
 
+                        // standalone line check part 1, for the leading whitespaces and newline
```
Comment (sunng87) [inline src/template.rs:601]: update comment to its latest  behaviour
